version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    image: backend:latest
    ports:
      - '8000:8000'