version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
  backend:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_NAME=plm_dev
      - JWT_SECRET_KEY=change-me
      - JWT_REFRESH_SECRET_KEY=change-refresh-me
      - ACCESS_TOKEN_EXPIRE_MINUTES=15
      - REFRESH_TOKEN_EXPIRE_DAYS=30
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data: